// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bar } from "./Bar";
import type { Excess } from "./Excess";
import type { Holds } from "./Holds";
import type { Kind } from "./Kind";
import type { Stability } from "./Stability";
import type { Stats } from "./Stats";

export type AggNode = { 
/**
 * стейдж
 */
position?: number, stats: Stats, id: string, kind: Kind, name: string, parent: string | null, children: Array<string>, deps: Array<string>, after: string | null, bar: Bar | null, 
/**
 * job, bridge, group: кто ждёт узел
 */
dependents?: Array<string>, 
/**
 * job, bridge, group: single — 0 или 1, агрегат — сумма долей шардов, не больше 1
 */
critShare?: number, 
/**
 * стейдж
 */
excess?: Excess, holds?: Holds, 
/**
 * лист, > 0
 */
retryLoss?: number, 
/**
 * лист агрегата или пайплайна из агрегата
 */
stability?: Stability, 
/**
 * сумма его hotspots
 */
saving?: number, };
