// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locale } from "./Locale";
import type { ProjectRef } from "./ProjectRef";
import type { Theme } from "./Theme";

export type AppSettings = { locale: Locale, theme: Theme, lastProject: ProjectRef | null, };
