// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Прошлая попытка ретраенной джобы.
 */
export type Attempt = { start: number | null, end: number | null, status: string, url: string, };
