// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorBody } from "./ErrorBody";
import type { Field } from "./Field";

/**
 * Что получает фронтенд от команды: общая ошибка или ошибки по полям формы (их возвращает только `build`).
 */
export type CmdError = { "kind": "message" } & ErrorBody | { "kind": "fields", errors: { [key in Field]?: ErrorBody }, };
