// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gap } from "./Gap";

/**
 * Критический путь scope: джобы в хронологическом порядке и ожидания между ними.
 */
export type Critical = { ids: Array<string>, gaps: Array<Gap>, };
