// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * Ошибка ядра: код и параметры, без готового текста.
 */
export type ErrorBody = { code: ErrorCode, params: { [key in string]: string }, };
