// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Код ошибки: перевод и подстановка `params` — на фронтенде.
 */
export type ErrorCode = "unauthorized" | "httpStatus" | "graphql" | "network" | "projectNotFound" | "pipelineNotFound" | "tooManyJobs" | "mrHasNoPipeline" | "noPipelines" | "noToken" | "emptyToken" | "keychainUnavailable" | "storage" | "invalidLink" | "invalidHost" | "invalidProject" | "invalidLast" | "invalidStatuses" | "forbidden" | "window" | "projectInputInvalid" | "projectDirNoRemote" | "reportExpired" | "rateLimited" | "workflowRequired";
