// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Узкое место стейджа: конец его последней джобы правее конца остальных.
 */
export type Excess = { id: string, peersEnd: number, excess: number, };
