// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Поле формы сборки, к которому относится ошибка.
 */
export type Field = "url" | "host" | "project" | "last" | "statuses" | "workflow";
