// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormMode } from "./FormMode";

/**
 * Форма как её заполнил пользователь: ничего не проверено, числа — текстом из поля.
 * Неизвестные поля (токен и прочее) при разборе отбрасываются.
 */
export type Form = { mode: FormMode, host: string, url: string, project: string, ref: string, source: string, last: string, 
/**
 * `ANY` — без фильтра
 */
statuses: Array<string>, 
/**
 * файл workflow GitHub (`ci.yml`); у GitLab форма шлёт пустую строку
 */
workflow: string, };
