// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ожидание между соседними джобами пути.
 */
export type Gap = { from: string, to: string, ms: number, };
