// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Подпись записи: форма рендерит её на текущем языке.
 */
export type HistoryLabel = { project: string, 
/**
 * как `meta.label`: `None` — «все пайплайны»
 */
label: string | null, };
