// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Form } from "./Form";
import type { HistoryLabel } from "./HistoryLabel";
import type { Request } from "./Request";

export type HistoryEntry = { 
/**
 * ISO 8601; он же идентификатор записи
 */
at: string, host: string, form: Form, request: Request, label: HistoryLabel, };
