// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Узел держит стейдж: его хвост правее остальных джоб стейджа.
 */
export type Holds = { stage: string, excess: number, };
