// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";
import type { TokenSource } from "./TokenSource";

export type HostInfo = { host: string, source: TokenSource, 
/**
 * `None` — хост из связки ключей, тип ещё не определён
 */
provider: Provider | null, };
