// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Пункт «Куда направить силы».
 */
export type Hotspot = { id: string, name: string, saving: number, } & ({ "kind": "retry", retries: number, } | { "kind": "retry", retried: number, present: number, } | { "kind": "excess", stage: string, excess: number, });
