// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Вид узла дерева.
 */
export type Kind = "pipeline" | "stage" | "group" | "job" | "bridge";
