// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locale } from "./Locale";
import type { Provider } from "./Provider";

export type Meta = { host: string, project: string, 
/**
 * `None` — «все пайплайны», текст подставляет отчёт на своём языке
 */
label: string | null, locale: Locale, statusCounts: { [key in string]: number } | null, 
/**
 * ISO 8601
 */
generatedAt: string, provider: Provider, 
/**
 * GitHub: файл workflow не загрузился — стейджи и связи джоб неизвестны
 */
needsMissing: boolean, };
