// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * p50 и p90; `null` — узел не запускался ни разу.
 */
export type P = { p50: number | null, p90: number | null, };
