// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Страница списка; `next` — курсор следующей страницы, `null` у последней.
 */
export type Page<T> = { items: Array<T>, next: string | null, };
