// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";

/**
 * Пайплайн в списке последних.
 */
export type Pipeline = { 
/**
 * число из gid
 */
id: string, iid: string, 
/**
 * строчными: `manual`, `running`
 */
status: string, source: string | null, createdAt: string, 
/**
 * мс
 */
duration: number | null, commit: Commit | null, author: string | null, };
