// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Сколько пайплайнов из скольких загружено.
 */
export type Progress = { loaded: number, total: number, };
