// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Проект на хосте: результат разбора ввода «Добавить проект» и ключ `projects.json`.
 */
export type ProjectRef = { host: string, path: string, };
