// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { 
/**
 * путь вида `group/sub/project`
 */
fullPath: string, name: string, lastActivityAt: string | null, defaultBranch: string | null, };
