// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggNode } from "./AggNode";
import type { Meta } from "./Meta";
import type { SingleNode } from "./SingleNode";
import type { Tree } from "./Tree";

export type Report = { "mode": "single", meta: Meta, tree: Tree<SingleNode>, } | { "mode": "aggregate", meta: Meta, agg: Tree<AggNode>, trees: Array<Tree<SingleNode>>, };
