// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

/**
 * Что строить. Хост — отдельно: он не часть запроса к проекту.
 */
export type Request = { "mode": "pipeline", project: string, pipelineId: string, } | { "mode": "mr", project: string, mrIid: string, } | { "mode": "aggregate", project: string, ref: string | null, source: string | null, last: number, 
/**
 * `None` — любые статусы
 */
statuses: Array<Status> | null, 
/**
 * файл workflow GitHub; старые записи истории — `None`
 */
workflow: string | null, };
