// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Один запуск узла: `tree` — индекс пайплайна в агрегате.
 */
export type Sample = { tree: number, start: number, end: number, retries: number, };
