// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SavedProject = { host: string, path: string, 
/**
 * `nameWithNamespace` из GitLab
 */
name: string, 
/**
 * ISO 8601
 */
addedAt: string, };
