// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locale } from "./Locale";
import type { ProjectRef } from "./ProjectRef";
import type { Theme } from "./Theme";

/**
 * Частичное обновление: `None` — поле не трогать.
 */
export type SettingsPatch = { locale?: Locale, theme?: Theme, lastProject?: ProjectRef, };
