// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attempt } from "./Attempt";
import type { Bar } from "./Bar";
import type { Excess } from "./Excess";
import type { Holds } from "./Holds";
import type { Kind } from "./Kind";
import type { Stability } from "./Stability";

export type SingleNode = { start: number | null, end: number | null, queued: number | null, status: string | null, allowFailure: boolean, url: string | null, attempts: Array<Attempt>, 
/**
 * пайплайн
 */
project?: string, ref?: string, id: string, kind: Kind, name: string, parent: string | null, children: Array<string>, deps: Array<string>, after: string | null, bar: Bar | null, 
/**
 * job, bridge, group: кто ждёт узел
 */
dependents?: Array<string>, 
/**
 * job, bridge, group: single — 0 или 1, агрегат — сумма долей шардов, не больше 1
 */
critShare?: number, 
/**
 * стейдж
 */
excess?: Excess, holds?: Holds, 
/**
 * лист, > 0
 */
retryLoss?: number, 
/**
 * лист агрегата или пайплайна из агрегата
 */
stability?: Stability, 
/**
 * сумма его hotspots
 */
saving?: number, };
