// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P } from "./P";
import type { Sample } from "./Sample";

/**
 * Статистика узла агрегата по пайплайнам, где он запускался.
 */
export type Stats = { present: number, total: number, start: P, end: P, duration: P, queued: P, 
/**
 * среднее число ретраев на запуск
 */
retries: number, 
/**
 * запусков с ретраями
 */
retried: number, 
/**
 * средняя потеря на ретраях, мс
 */
retryLoss: number, 
/**
 * доля пайплайнов, где узел на критическом пути; у стейджа и группы всегда 0
 */
critical: number, samples: Array<Sample>, };
