// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Откуда у хоста токен; «Удалить» в настройках есть только у `Keychain`.
 */
export type TokenSource = "keychain" | "glab" | "env" | "gh";
