// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Critical } from "./Critical";
import type { Hotspot } from "./Hotspot";

export type Tree<N> = { root: string, nodes: { [key in string]: N }, 
/**
 * по scope: в single — пайплайны и стейджи, в агрегате — только корень
 */
critical: { [key in string]: Critical }, hotspots: Array<Hotspot>, totalRetryLoss: number, saving: number, };
