// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow GitHub Actions; `file` — имя файла (`ci.yml`), им фильтруют запуски.
 */
export type Workflow = { file: string, name: string, };
