[package]
name = "pipeline-trace"
version = "0.0.0"
edition = "2024"
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
time = "0.3"
pipeline-trace-core = { path = "../core" }
