//! Словарь Rust: только меню и ошибка сохранения; остальное переводит фронтенд.

use longpole_core::schema::Locale;

pub struct Strings {
    pub about: &'static str,
    pub hide: &'static str,
    pub hide_others: &'static str,
    pub show_all: &'static str,
    pub services: &'static str,
    pub quit: &'static str,
    pub file: &'static str,
    pub new_report: &'static str,
    pub save_report: &'static str,
    pub close_window: &'static str,
    pub exit: &'static str,
    pub edit: &'static str,
    pub undo: &'static str,
    pub redo: &'static str,
    pub cut: &'static str,
    pub copy: &'static str,
    pub paste: &'static str,
    pub select_all: &'static str,
    pub view: &'static str,
    pub zoom_reset: &'static str,
    pub zoom_in: &'static str,
    pub zoom_out: &'static str,
    pub fullscreen: &'static str,
    pub window: &'static str,
    pub minimize: &'static str,
    pub maximize: &'static str,
    pub save_error: &'static str,
}

const RU: Strings = Strings {
    about: "О программе Longpole",
    hide: "Скрыть Longpole",
    hide_others: "Скрыть остальные",
    show_all: "Показать все",
    services: "Службы",
    quit: "Завершить Longpole",
    file: "Файл",
    new_report: "Новый отчёт",
    save_report: "Сохранить отчёт…",
    close_window: "Закрыть окно",
    exit: "Выход",
    edit: "Правка",
    undo: "Отменить",
    redo: "Повторить",
    cut: "Вырезать",
    copy: "Копировать",
    paste: "Вставить",
    select_all: "Выделить всё",
    view: "Вид",
    zoom_reset: "Фактический размер",
    zoom_in: "Увеличить",
    zoom_out: "Уменьшить",
    fullscreen: "Во весь экран",
    window: "Окно",
    minimize: "Свернуть",
    maximize: "Развернуть",
    save_error: "Не удалось сохранить отчёт",
};

const EN: Strings = Strings {
    about: "About Longpole",
    hide: "Hide Longpole",
    hide_others: "Hide Others",
    show_all: "Show All",
    services: "Services",
    quit: "Quit Longpole",
    file: "File",
    new_report: "New Report",
    save_report: "Save Report…",
    close_window: "Close Window",
    exit: "Exit",
    edit: "Edit",
    undo: "Undo",
    redo: "Redo",
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    select_all: "Select All",
    view: "View",
    zoom_reset: "Actual Size",
    zoom_in: "Zoom In",
    zoom_out: "Zoom Out",
    fullscreen: "Toggle Full Screen",
    window: "Window",
    minimize: "Minimize",
    maximize: "Zoom",
    save_error: "Could not save the report",
};

const FR: Strings = Strings {
    about: "À propos de Longpole",
    hide: "Masquer Longpole",
    hide_others: "Masquer les autres",
    show_all: "Tout afficher",
    services: "Services",
    quit: "Quitter Longpole",
    file: "Fichier",
    new_report: "Nouveau rapport",
    save_report: "Enregistrer le rapport…",
    close_window: "Fermer la fenêtre",
    exit: "Quitter",
    edit: "Édition",
    undo: "Annuler",
    redo: "Rétablir",
    cut: "Couper",
    copy: "Copier",
    paste: "Coller",
    select_all: "Tout sélectionner",
    view: "Présentation",
    zoom_reset: "Taille réelle",
    zoom_in: "Zoom avant",
    zoom_out: "Zoom arrière",
    fullscreen: "Plein écran",
    window: "Fenêtre",
    minimize: "Placer dans le Dock",
    maximize: "Réduire/agrandir",
    save_error: "Impossible d’enregistrer le rapport",
};

const ES: Strings = Strings {
    about: "Acerca de Longpole",
    hide: "Ocultar Longpole",
    hide_others: "Ocultar otros",
    show_all: "Mostrar todo",
    services: "Servicios",
    quit: "Salir de Longpole",
    file: "Archivo",
    new_report: "Nuevo informe",
    save_report: "Guardar informe…",
    close_window: "Cerrar ventana",
    exit: "Salir",
    edit: "Edición",
    undo: "Deshacer",
    redo: "Rehacer",
    cut: "Cortar",
    copy: "Copiar",
    paste: "Pegar",
    select_all: "Seleccionar todo",
    view: "Visualización",
    zoom_reset: "Tamaño real",
    zoom_in: "Ampliar",
    zoom_out: "Reducir",
    fullscreen: "Pantalla completa",
    window: "Ventana",
    minimize: "Minimizar",
    maximize: "Zoom",
    save_error: "No se pudo guardar el informe",
};

const DE: Strings = Strings {
    about: "Über Longpole",
    hide: "Longpole ausblenden",
    hide_others: "Andere ausblenden",
    show_all: "Alle einblenden",
    services: "Dienste",
    quit: "Longpole beenden",
    file: "Ablage",
    new_report: "Neuer Bericht",
    save_report: "Bericht sichern …",
    close_window: "Fenster schließen",
    exit: "Beenden",
    edit: "Bearbeiten",
    undo: "Widerrufen",
    redo: "Wiederholen",
    cut: "Ausschneiden",
    copy: "Kopieren",
    paste: "Einsetzen",
    select_all: "Alles auswählen",
    view: "Darstellung",
    zoom_reset: "Originalgröße",
    zoom_in: "Vergrößern",
    zoom_out: "Verkleinern",
    fullscreen: "Vollbildmodus",
    window: "Fenster",
    minimize: "Im Dock ablegen",
    maximize: "Zoomen",
    save_error: "Bericht konnte nicht gesichert werden",
};

const IT: Strings = Strings {
    about: "Informazioni su Longpole",
    hide: "Nascondi Longpole",
    hide_others: "Nascondi altre",
    show_all: "Mostra tutte",
    services: "Servizi",
    quit: "Esci da Longpole",
    file: "File",
    new_report: "Nuovo report",
    save_report: "Salva report…",
    close_window: "Chiudi finestra",
    exit: "Esci",
    edit: "Modifica",
    undo: "Annulla",
    redo: "Ripeti",
    cut: "Taglia",
    copy: "Copia",
    paste: "Incolla",
    select_all: "Seleziona tutto",
    view: "Vista",
    zoom_reset: "Dimensioni reali",
    zoom_in: "Ingrandisci",
    zoom_out: "Riduci",
    fullscreen: "Schermo intero",
    window: "Finestra",
    minimize: "Contrai",
    maximize: "Ridimensiona",
    save_error: "Impossibile salvare il report",
};

const ZH: Strings = Strings {
    about: "关于 Longpole",
    hide: "隐藏 Longpole",
    hide_others: "隐藏其他",
    show_all: "全部显示",
    services: "服务",
    quit: "退出 Longpole",
    file: "文件",
    new_report: "新建报告",
    save_report: "保存报告…",
    close_window: "关闭窗口",
    exit: "退出",
    edit: "编辑",
    undo: "撤销",
    redo: "重做",
    cut: "剪切",
    copy: "拷贝",
    paste: "粘贴",
    select_all: "全选",
    view: "显示",
    zoom_reset: "实际大小",
    zoom_in: "放大",
    zoom_out: "缩小",
    fullscreen: "全屏",
    window: "窗口",
    minimize: "最小化",
    maximize: "缩放",
    save_error: "无法保存报告",
};

const JA: Strings = Strings {
    about: "Longpole について",
    hide: "Longpole を非表示",
    hide_others: "ほかを非表示",
    show_all: "すべてを表示",
    services: "サービス",
    quit: "Longpole を終了",
    file: "ファイル",
    new_report: "新規レポート",
    save_report: "レポートを保存…",
    close_window: "ウインドウを閉じる",
    exit: "終了",
    edit: "編集",
    undo: "取り消す",
    redo: "やり直す",
    cut: "カット",
    copy: "コピー",
    paste: "ペースト",
    select_all: "すべてを選択",
    view: "表示",
    zoom_reset: "実際のサイズ",
    zoom_in: "拡大",
    zoom_out: "縮小",
    fullscreen: "フルスクリーン",
    window: "ウインドウ",
    minimize: "しまう",
    maximize: "拡大/縮小",
    save_error: "レポートを保存できませんでした",
};

pub fn strings(locale: Locale) -> &'static Strings {
    match locale {
        Locale::Ru => &RU,
        Locale::En => &EN,
        Locale::Fr => &FR,
        Locale::Es => &ES,
        Locale::De => &DE,
        Locale::It => &IT,
        Locale::Zh => &ZH,
        Locale::Ja => &JA,
    }
}
