//! Словарь Rust: только меню и ошибка сохранения; остальное переводит фронтенд.

use pipeline_trace_core::schema::Locale;

pub struct Strings {
    pub about: &'static str,
    pub hide: &'static str,
    pub hide_others: &'static str,
    pub show_all: &'static str,
    pub services: &'static str,
    pub quit: &'static str,
    pub file: &'static str,
    pub new_report: &'static str,
    pub save_report: &'static str,
    pub close_window: &'static str,
    pub exit: &'static str,
    pub edit: &'static str,
    pub undo: &'static str,
    pub redo: &'static str,
    pub cut: &'static str,
    pub copy: &'static str,
    pub paste: &'static str,
    pub select_all: &'static str,
    pub view: &'static str,
    pub zoom_reset: &'static str,
    pub zoom_in: &'static str,
    pub zoom_out: &'static str,
    pub fullscreen: &'static str,
    pub window: &'static str,
    pub minimize: &'static str,
    pub maximize: &'static str,
    pub save_error: &'static str,
}

const RU: Strings = Strings {
    about: "О программе pipeline-trace",
    hide: "Скрыть pipeline-trace",
    hide_others: "Скрыть остальные",
    show_all: "Показать все",
    services: "Службы",
    quit: "Завершить pipeline-trace",
    file: "Файл",
    new_report: "Новый отчёт",
    save_report: "Сохранить отчёт…",
    close_window: "Закрыть окно",
    exit: "Выход",
    edit: "Правка",
    undo: "Отменить",
    redo: "Повторить",
    cut: "Вырезать",
    copy: "Копировать",
    paste: "Вставить",
    select_all: "Выделить всё",
    view: "Вид",
    zoom_reset: "Фактический размер",
    zoom_in: "Увеличить",
    zoom_out: "Уменьшить",
    fullscreen: "Во весь экран",
    window: "Окно",
    minimize: "Свернуть",
    maximize: "Развернуть",
    save_error: "Не удалось сохранить отчёт",
};

const EN: Strings = Strings {
    about: "About pipeline-trace",
    hide: "Hide pipeline-trace",
    hide_others: "Hide Others",
    show_all: "Show All",
    services: "Services",
    quit: "Quit pipeline-trace",
    file: "File",
    new_report: "New Report",
    save_report: "Save Report…",
    close_window: "Close Window",
    exit: "Exit",
    edit: "Edit",
    undo: "Undo",
    redo: "Redo",
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    select_all: "Select All",
    view: "View",
    zoom_reset: "Actual Size",
    zoom_in: "Zoom In",
    zoom_out: "Zoom Out",
    fullscreen: "Toggle Full Screen",
    window: "Window",
    minimize: "Minimize",
    maximize: "Zoom",
    save_error: "Could not save the report",
};

pub fn strings(locale: Locale) -> &'static Strings {
    match locale {
        Locale::Ru => &RU,
        Locale::En => &EN,
    }
}
